name: Deploy

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        os-version: [ubuntu-latest]
        node-version: [18.x]
    runs-on: ${{ matrix.os-version }}

    steps:
    - name: Clone Repo
      uses: actions/checkout@v3.0.2

    - name: Prepare java
      uses: actions/setup-java@v3.3.0
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install clojure cli
      uses: DeLaGuardo/setup-clojure@master
      with:
        cli: 1.12.0.1488

    - name: Test ${{ matrix.node-version }}
      uses: actions/setup-node@v3.2.0
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm install
        npm run ci-tests

  deploy:
    needs: [tests]
    strategy:
      matrix:
        os-version: [ubuntu-latest]
        node-version: [16.x]
    runs-on: ubuntu-latest

    steps:
    - name: Clone Repo
      uses: actions/checkout@v3.0.2

    - name: Prepare java
      uses: actions/setup-java@v3.3.0
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install clojure cli
      uses: DeLaGuardo/setup-clojure@master
      with:
        cli: 1.12.0.1488

    - name: Build ${{ matrix.node-version }}
      uses: actions/setup-node@v3.2.0
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm install
        npm run release

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        cname: lanjoni.dev 
